services:
  first-microservice:
    container_name: first-microservice
    build: ./first-microservice
    ports:
      - "8080:8080"
    environment:
      - SECOND_MICROSERVICE_URI=http://second-microservice:8081
  second-microservice:
    container_name: second-microservice
    build: ./second-microservice
    ports:
      - "8081:8081"