{{- if .Values.gateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-gateway
  labels: {{ include "otel.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{ include "otel.labels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "otel.labels" . | nindent 8 }}
    spec:
      containers:
        - name: otel-gateway
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          command: ["/otelcol-contrib", "--config=/conf/gateway-config.yaml"]
          ports:
            - name: grpc
              containerPort: {{ .Values.gateway.service.grpcPort }}
            - name: http
              containerPort: {{ .Values.gateway.service.httpPort }}
          volumeMounts:
            - name: config
              mountPath: /conf
          resources: {{ toYaml .Values.gateway.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-gateway-config
{{- end }}